stages: 
  - deploy

deploy_live:
    image: "docker:latest"
    services:
      - docker:dind
    script: 
     - docker build -t docker.jbuncle.co.uk/jbuncle/php-docker .
     - docker push docker.jbuncle.co.uk/jbuncle/php-docker
    stage: deploy
    only: 
     - master
