#!/bin/bash
set -e

PHPVERSION=8.3
DOCKER_REPO=cyberpearuk/php-build-docker

if [ "$DOCKER_TAG" == "latest" ] ; then 
    docker build --build-arg PHPVERSION=$PHPVERSION -t $DOCKER_REPO:$PHPVERSION .
    
    # Set latest
    docker tag $DOCKER_REPO:7.4 $DOCKER_REPO:latest
else
    docker build --build-arg PHPVERSION=$PHPVERSION -t $DOCKER_REPO::$DOCKER_TAG-$PHPVERSION .

    # Set latest
    docker tag $DOCKER_REPO:$DOCKER_TAG-$PHPVERSION $DOCKER_REPO:$DOCKER_TAG
fi

