#!/bin/bash
set -e

PHPVERSION=8.3

if [ "$DOCKER_TAG" == "latest" ] ; then 
    docker push $DOCKER_REPO:$PHPVERSION
    docker push $DOCKER_REPO:latest
else

    docker push $DOCKER_REPO:$DOCKER_TAG-$PHPVERSION
    docker push $DOCKER_REPO:$DOCKER_TAG
fi

