#!/bin/bash
set -e

if [ "$DOCKER_TAG" == "latest" ] ; then 
    docker push $DOCKER_REPO:7.4
    docker push $DOCKER_REPO:8.0
    docker push $DOCKER_REPO:latest
else

    docker push $DOCKER_REPO:$DOCKER_TAG-7.4
    docker push $DOCKER_REPO:$DOCKER_TAG-8.0
    docker push $DOCKER_REPO:$DOCKER_TAG
fi

